<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OB8BAPB" failures="1" tests="3" name="Negative" time="8.225" errors="0" timestamp="2023-09-07T13:33:03 IST">
  <testcase classname="com.BestBuy.test.NegativeTc_SignIn" name="signInWithInValidCredentials" time="0.052"/>
  <testcase classname="com.BestBuy.test.NegativeTc_ItemsAddedToCart" name="ItemsAddedCartTestWithInvalidCredentials" time="8.044"/>
  <testcase classname="com.BestBuy.test.NegativeTc_SignUp" name="signUpWithInValidCredentials" time="0.116">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.BestBuy.test.NegativeTc_SignUp.signUpWithInValidCredentials(NegativeTc_SignUp.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- signUpWithInValidCredentials -->
</testsuite> <!-- Negative -->
